// let rectsize = 50;
// let x = 1500/2
// let y = 700/2

// function setup() {
//     createCanvas(1500, 700);
// background(220)
// }
// let size = 5;

// function draw(){
//     noStroke();
//     rect(x,y,20,20);
//     fill('green')
//     if (keyIsDown (87)){
//          y = y - 1;
//      }
//     if (keyIsDown (65)){
//          x = x - 1;
//      }
//      if (keyIsDown (83)){
//          y = y + 1;
//      }
//      if (keyIsDown (68)){
//          x = x + 1;
//      }
// }

//  function keyPressed(){
// //     if (key === 'w'){
// //         y = y - 20
// //     }
// //     else if (key === 's'){
// //         y=y+20
// //     }
// //     else if (key === 'd'){
// //         x=x+20
// //     }
// //     else if (key === 'a'){
// //         x=x-20
// //     }
// //     // rectsize = 100;
//  }

// // function keyReleased(){
// //     rectsize = 50;
// // }
// // function mousePressed(){
// //     fill(random(255),random(255),random(255));
// //     size = 5;
// // }
// // function mouseDragged(){
// //     circle(mouseX,mouseY,size=size+0.5);
// // }
